globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: win
autosplit: true
concurrency: 114
testDiscoverer: grep 'test name' src/test/java/Win10.xml | awk '{print$2}' | sed 's/name=//g' | sed 's/\x3e//g'
testRunnerCommand: mvn test `-DselectedTests="$test" `-DLT_USERNAME=prateeks `-DLT_ACCESS_KEY= `-DGRID_URL=stage-hub.lambdatest.com `-DBUILD_NAME=HYperTest-win
#pre:
#  - mvn -Dmaven.repo.local=./.m2 dependency:resolve
#cacheKey: '{{ checksum "pom.xml" }}'
cacheDirectories:
  - .m2

  