globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: linux
autosplit: true
concurrency: 114
joblable: ["TestSHeet"]
testDiscoverer: grep 'test name' src/test/java/LinuxHunred.xml | awk '{print$2}' | sed 's/name=//g' | sed 's/\x3e//g'
testRunnerCommand: mvn test -DselectedTests="$test" -Dsurefire.suiteXmlFiles=src/test/java/LinuxHunred.xml -DLT_USERNAME=prateeks -DLT_ACCESS_KEY= -DGRID_URL=stage-hub.lambdatest.com -DBUILD_NAME=HYperTest-Linux-SmallTest-SeleniumVersion
#pre:
#  - mvn -Dmaven.repo.local=./.m2 dependency:resolve
#cacheKey: '{{ checksum "pom.xml" }}'
#cacheDirectories:

#  - .m2

mergeArtifacts: true
stripParentDirectory: true
taskIdentifierInNonConflictingArtefacts: true